#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, MOUSE, PUSHFRONT, PUSHBACK};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET, CUSTOM};

enum ACTION {NONE, UNDO, CLEAR, INCREASE, DECREASE};

#endif